export enum ACTIONS {
  SET_HAS_INIT_DATA_ERROR = "SET_HAS_INIT_DATA_ERROR",
  SET_INITIAL_DATA = "SET_INITIAL_DATA",
  SET_SEARCH_RESULT = "SET_SEARCH_RESULT",
  SELECT_SEARCH_COMMUNE = "SELECT_SEARCH_COMMUNE",
  SELECT_EXPLORE_COMMUNE = "SELECT_EXPLORE_COMMUNE",
  SET_TAB = "SET_TAB",
  SET_SEARCH = "SET_SEARCH",
  SET_IS_SEARCHING = "SET_IS_SEARCHING",
  SET_IS_LOADING_SEARCH_COMMUNE = "SET_IS_LOADING_SEARCH_COMMUNE",
  SET_IS_LOADING_EXPLORE_COMMUNE = "SET_IS_LOADING_EXPLORE_COMMUNE",
  SELECT_REGION = "SELECT_REGION",
  SELECT_DEPARTEMENT = "SELECT_DEPARTEMENT",
  SET_IS_LOADING_DEPARTEMENT_COMMUNES = "SET_IS_LOADING_DEPARTEMENT_COMMUNES",
  SET_DEPARTEMENT_COMMUNES = "SET_DEPARTEMENT_COMMUNES"
}
